function delta = GimbalCommandPlanar(t,p)

delta = interp1(p.gimbalTime, ...
                p.gimbalData, ...
                t, ...
                'linear', ...
                0);

delta = max(min(delta,p.deltaMax),-p.deltaMax);

end